# Generated by Django 2.0.7 on 2019-05-01 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_provisioning', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
