# Generated by Django 2.0.7 on 2019-05-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_provisioning', '0004_tenant_tenantid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='tenantId',
            field=models.TextField(default='null'),
        ),
    ]
